package com.video.CodeHelp.Enums;


public enum TestCaseGeneratorRules {
  GENERATE_RANDOM_INTEGER_ARRAY,
  STRING_ARRAY,STRING,INTEGER,
  TREE,BINARY_TREE,
  SORT,
  GENERATE_INTEGER_ARRAY,
  SORT_ARRAY,
  GENERATE_UNIQUE_ARRAY,
  GENERATE_POSITIVE_NEGATIVE_ARRAY,
  GENERATE_POSITIVE_NEGATIVE_UNIQUE_ARRAY,
  GENERATE_RANDOM_INTEGER,
  SORT_DIGITS_IN_ASC,
  SORT_DIGITS_IN_DESC;
}
